// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ecocraft.Migrations
{
    [DbContext(typeof(EcoCraftDbContext))]
    partial class EcoCraftDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.8");

            modelBuilder.Entity("CraftingTablePluginModule", b =>
                {
                    b.Property<Guid>("CraftingTableId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PluginModuleId")
                        .HasColumnType("TEXT");

                    b.HasKey("CraftingTableId", "PluginModuleId");

                    b.HasIndex("PluginModuleId");

                    b.ToTable("CraftingTablePluginModule");
                });

            modelBuilder.Entity("ItemTagAssoc", b =>
                {
                    b.Property<Guid>("TagId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("TEXT");

                    b.HasKey("TagId", "ItemId");

                    b.HasIndex("ItemId");

                    b.ToTable("ItemTagAssoc");
                });

            modelBuilder.Entity("UserServer", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ServerId")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "ServerId");

                    b.HasIndex("ServerId");

                    b.ToTable("UserServer");
                });

            modelBuilder.Entity("ecocraft.Models.CraftingTable", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ServerId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ServerId");

                    b.ToTable("CraftingTables");
                });

            modelBuilder.Entity("ecocraft.Models.Element", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDynamic")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("ItemOrTagId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("LavishTalent")
                        .HasColumnType("INTEGER");

                    b.Property<float>("Quantity")
                        .HasColumnType("REAL");

                    b.Property<Guid>("RecipeId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("SkillId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ItemOrTagId");

                    b.HasIndex("RecipeId");

                    b.HasIndex("SkillId");

                    b.ToTable("Elements");
                });

            modelBuilder.Entity("ecocraft.Models.ItemOrTag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsTag")
                        .HasColumnType("INTEGER");

                    b.Property<float>("MaxPrice")
                        .HasColumnType("REAL");

                    b.Property<float>("MinPrice")
                        .HasColumnType("REAL");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ServerId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ServerId");

                    b.ToTable("ItemOrTags");
                });

            modelBuilder.Entity("ecocraft.Models.PluginModule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<float>("Percent")
                        .HasColumnType("REAL");

                    b.Property<Guid>("ServerId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ServerId");

                    b.ToTable("PluginModules");
                });

            modelBuilder.Entity("ecocraft.Models.Recipe", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<float>("CraftMinutes")
                        .HasColumnType("REAL");

                    b.Property<Guid>("CraftingTableId")
                        .HasColumnType("TEXT");

                    b.Property<string>("FamilyName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsBlueprint")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("INTEGER");

                    b.Property<float>("Labor")
                        .HasColumnType("REAL");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ServerId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("SkillId")
                        .HasColumnType("TEXT");

                    b.Property<long>("SkillLevel")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CraftingTableId");

                    b.HasIndex("ServerId");

                    b.HasIndex("SkillId");

                    b.ToTable("Recipes");
                });

            modelBuilder.Entity("ecocraft.Models.Server", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SecretId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Servers");
                });

            modelBuilder.Entity("ecocraft.Models.Skill", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ServerId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ServerId");

                    b.ToTable("Skills");
                });

            modelBuilder.Entity("ecocraft.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Pseudo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SecretId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("ecocraft.Models.UserCraftingTable", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CraftingTableId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PluginModuleId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CraftingTableId");

                    b.HasIndex("PluginModuleId");

                    b.HasIndex("UserId");

                    b.ToTable("UserCraftingTables");
                });

            modelBuilder.Entity("ecocraft.Models.UserElement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ElementId")
                        .HasColumnType("TEXT");

                    b.Property<float>("Share")
                        .HasColumnType("REAL");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ElementId");

                    b.HasIndex("UserId");

                    b.ToTable("UserElements");
                });

            modelBuilder.Entity("ecocraft.Models.UserPrice", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ItemOrTagId")
                        .HasColumnType("TEXT");

                    b.Property<float>("Price")
                        .HasColumnType("REAL");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ItemOrTagId");

                    b.HasIndex("UserId");

                    b.ToTable("UserPrices");
                });

            modelBuilder.Entity("ecocraft.Models.UserSetting", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<float>("CalorieCost")
                        .HasColumnType("REAL");

                    b.Property<float>("Margin")
                        .HasColumnType("REAL");

                    b.Property<Guid>("ServerId")
                        .HasColumnType("TEXT");

                    b.Property<float>("TimeFee")
                        .HasColumnType("REAL");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ServerId");

                    b.HasIndex("UserId");

                    b.ToTable("UserSettings");
                });

            modelBuilder.Entity("ecocraft.Models.UserSkill", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("HasLavishTalent")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Level")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("SkillId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SkillId");

                    b.HasIndex("UserId");

                    b.ToTable("UserSkills");
                });

            modelBuilder.Entity("CraftingTablePluginModule", b =>
                {
                    b.HasOne("ecocraft.Models.CraftingTable", null)
                        .WithMany()
                        .HasForeignKey("CraftingTableId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ecocraft.Models.PluginModule", null)
                        .WithMany()
                        .HasForeignKey("PluginModuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ItemTagAssoc", b =>
                {
                    b.HasOne("ecocraft.Models.ItemOrTag", null)
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ecocraft.Models.ItemOrTag", null)
                        .WithMany()
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("UserServer", b =>
                {
                    b.HasOne("ecocraft.Models.Server", null)
                        .WithMany()
                        .HasForeignKey("ServerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ecocraft.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ecocraft.Models.CraftingTable", b =>
                {
                    b.HasOne("ecocraft.Models.Server", "Server")
                        .WithMany("CraftingTables")
                        .HasForeignKey("ServerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Server");
                });

            modelBuilder.Entity("ecocraft.Models.Element", b =>
                {
                    b.HasOne("ecocraft.Models.ItemOrTag", "ItemOrTag")
                        .WithMany("Elements")
                        .HasForeignKey("ItemOrTagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ecocraft.Models.Recipe", "Recipe")
                        .WithMany("Elements")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ecocraft.Models.Skill", "Skill")
                        .WithMany()
                        .HasForeignKey("SkillId");

                    b.Navigation("ItemOrTag");

                    b.Navigation("Recipe");

                    b.Navigation("Skill");
                });

            modelBuilder.Entity("ecocraft.Models.ItemOrTag", b =>
                {
                    b.HasOne("ecocraft.Models.Server", "Server")
                        .WithMany("ItemOrTags")
                        .HasForeignKey("ServerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Server");
                });

            modelBuilder.Entity("ecocraft.Models.PluginModule", b =>
                {
                    b.HasOne("ecocraft.Models.Server", "Server")
                        .WithMany("PluginModules")
                        .HasForeignKey("ServerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Server");
                });

            modelBuilder.Entity("ecocraft.Models.Recipe", b =>
                {
                    b.HasOne("ecocraft.Models.CraftingTable", "CraftingTable")
                        .WithMany("Recipes")
                        .HasForeignKey("CraftingTableId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ecocraft.Models.Server", "Server")
                        .WithMany("Recipes")
                        .HasForeignKey("ServerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ecocraft.Models.Skill", "Skill")
                        .WithMany("Recipes")
                        .HasForeignKey("SkillId");

                    b.Navigation("CraftingTable");

                    b.Navigation("Server");

                    b.Navigation("Skill");
                });

            modelBuilder.Entity("ecocraft.Models.Skill", b =>
                {
                    b.HasOne("ecocraft.Models.Server", "Server")
                        .WithMany("Skills")
                        .HasForeignKey("ServerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Server");
                });

            modelBuilder.Entity("ecocraft.Models.UserCraftingTable", b =>
                {
                    b.HasOne("ecocraft.Models.CraftingTable", "CraftingTable")
                        .WithMany("UserCraftingTables")
                        .HasForeignKey("CraftingTableId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ecocraft.Models.PluginModule", "PluginModule")
                        .WithMany()
                        .HasForeignKey("PluginModuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ecocraft.Models.User", "User")
                        .WithMany("UserCraftingTables")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CraftingTable");

                    b.Navigation("PluginModule");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ecocraft.Models.UserElement", b =>
                {
                    b.HasOne("ecocraft.Models.Element", "Element")
                        .WithMany("UserElements")
                        .HasForeignKey("ElementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ecocraft.Models.User", "User")
                        .WithMany("UserElements")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Element");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ecocraft.Models.UserPrice", b =>
                {
                    b.HasOne("ecocraft.Models.ItemOrTag", "ItemOrTag")
                        .WithMany("UserPrices")
                        .HasForeignKey("ItemOrTagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ecocraft.Models.User", "User")
                        .WithMany("UserPrices")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ItemOrTag");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ecocraft.Models.UserSetting", b =>
                {
                    b.HasOne("ecocraft.Models.Server", "Server")
                        .WithMany("UserSettings")
                        .HasForeignKey("ServerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ecocraft.Models.User", "User")
                        .WithMany("UserSettings")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Server");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ecocraft.Models.UserSkill", b =>
                {
                    b.HasOne("ecocraft.Models.Skill", "Skill")
                        .WithMany("UserSkills")
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ecocraft.Models.User", "User")
                        .WithMany("UserSkills")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Skill");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ecocraft.Models.CraftingTable", b =>
                {
                    b.Navigation("Recipes");

                    b.Navigation("UserCraftingTables");
                });

            modelBuilder.Entity("ecocraft.Models.Element", b =>
                {
                    b.Navigation("UserElements");
                });

            modelBuilder.Entity("ecocraft.Models.ItemOrTag", b =>
                {
                    b.Navigation("Elements");

                    b.Navigation("UserPrices");
                });

            modelBuilder.Entity("ecocraft.Models.Recipe", b =>
                {
                    b.Navigation("Elements");
                });

            modelBuilder.Entity("ecocraft.Models.Server", b =>
                {
                    b.Navigation("CraftingTables");

                    b.Navigation("ItemOrTags");

                    b.Navigation("PluginModules");

                    b.Navigation("Recipes");

                    b.Navigation("Skills");

                    b.Navigation("UserSettings");
                });

            modelBuilder.Entity("ecocraft.Models.Skill", b =>
                {
                    b.Navigation("Recipes");

                    b.Navigation("UserSkills");
                });

            modelBuilder.Entity("ecocraft.Models.User", b =>
                {
                    b.Navigation("UserCraftingTables");

                    b.Navigation("UserElements");

                    b.Navigation("UserPrices");

                    b.Navigation("UserSettings");

                    b.Navigation("UserSkills");
                });
#pragma warning restore 612, 618
        }
    }
}
