// <auto-generated />
// Régénérer : python ecocraft/Scripts/gen-block-colors.py [export v5]
// Couleur dominante de l'icône du bloc, écartée en luminosité entre matériaux confondables.

using System.Collections.Frozen;

namespace ecocraft.BuildingPlanner;

public static partial class BlockColors
{
    static readonly FrozenDictionary<string, string> Generated = new Dictionary<string, string>(StringComparer.Ordinal)
    {
        { "AsphaltConcreteItem", "#606060" },                     // T0 Asphalt Concrete
        { "CrushedBasaltItem", "#4c5055" },                       // T0 Crushed Basalt
        { "CrushedCoalItem", "#595857" },                         // T0 Crushed Coal
        { "CrushedCopperOreItem", "#a16348" },                    // T0 Crushed Copper Ore
        { "CrushedGneissItem", "#8e836b" },                       // T0 Crushed Gneiss
        { "CrushedGoldOreItem", "#989590" },                      // T0 Crushed Gold Ore
        { "CrushedGraniteItem", "#a19e99" },                      // T0 Crushed Granite
        { "CrushedIronOreItem", "#ae491b" },                      // T0 Crushed Iron Ore
        { "CrushedLimestoneItem", "#a9997d" },                    // T0 Crushed Limestone
        { "CrushedMixedRockItem", "#7e7a74" },                    // T0 Crushed Mixed Rock
        { "CrushedSandstoneItem", "#c0682c" },                    // T0 Crushed Sandstone
        { "CrushedShaleItem", "#666972" },                        // T0 Crushed Shale
        { "CrushedSlagItem", "#7c8585" },                         // T0 Crushed Slag
        { "CrushedSulfurItem", "#b89605" },                       // T0 Crushed Sulfur
        { "DirtItem", "#6f3700" },                                // T0 Dirt
        { "GardenGravelItem", "#cecece" },                        // T0 Garden Gravel
        { "StoneRoadItem", "#8080a9" },                           // T0 Stone Road
        { "AdobeItem", "#a77e5b" },                               // T1 Adobe
        { "HardwoodHewnLogItem", "#72431b" },                     // T2 Hardwood Hewn Log
        { "HewnLogItem", "#cd8951" },                             // T2 Hewn Log
        { "MortaredGraniteItem", "#668299" },                     // T2 Mortared Granite
        { "MortaredLimestoneItem", "#97b9b7" },                   // T2 Mortared Limestone
        { "MortaredSandstoneItem", "#944c1e" },                   // T2 Mortared Sandstone
        { "MortaredStoneItem", "#6598da" },                       // T2 Mortared Stone
        { "SoftwoodHewnLogItem", "#b98455" },                     // T2 Softwood Hewn Log
        { "BrickItem", "#a85f30" },                               // T3 Brick
        { "FarEastLumberItem", "#9e5757" },                       // T3 Far East Lumber
        { "GlassItem", "#d6d8d6" },                               // T3 Glass
        { "HardwoodLumberItem", "#e09b4d" },                      // T3 Hardwood Lumber
        { "LumberItem", "#d29660" },                              // T3 Lumber
        { "SoftwoodLumberItem", "#f8d0a0" },                      // T3 Softwood Lumber
        { "CorrugatedSteelItem", "#b8bbbc" },                     // T4 Corrugated Steel
        { "ReinforcedConcreteItem", "#bbc6cd" },                  // T4 Reinforced Concrete
        { "AshlarBasaltItem", "#414a4a" },                        // T5 Ashlar Basalt
        { "AshlarGneissItem", "#7d5445" },                        // T5 Ashlar Gneiss
        { "AshlarGraniteItem", "#858e8e" },                       // T5 Ashlar Granite
        { "AshlarLimestoneItem", "#9c9d7e" },                     // T5 Ashlar Limestone
        { "AshlarSandstoneItem", "#8f3900" },                     // T5 Ashlar Sandstone
        { "AshlarShaleItem", "#6c7376" },                         // T5 Ashlar Shale
        { "CompositeBirchLumberItem", "#e2ad71" },                // T5 Composite Birch Lumber
        { "CompositeCedarLumberItem", "#d4833e" },                // T5 Composite Cedar Lumber
        { "CompositeCeibaLumberItem", "#caa87e" },                // T5 Composite Ceiba Lumber
        { "CompositeFirLumberItem", "#febe87" },                  // T5 Composite Fir Lumber
        { "CompositeJoshuaLumberItem", "#ffae64" },               // T5 Composite Joshua Lumber
        { "CompositeLumberItem", "#efb67d" },                     // T5 Composite Lumber
        { "CompositeOakLumberItem", "#a77125" },                  // T5 Composite Oak Lumber
        { "CompositePalmLumberItem", "#f6954e" },                 // T5 Composite Palm Lumber
        { "CompositeRedwoodLumberItem", "#834729" },              // T5 Composite Redwood Lumber
        { "CompositeSaguaroLumberItem", "#836b34" },              // T5 Composite Saguaro Lumber
        { "CompositeSpruceLumberItem", "#cfad6d" },               // T5 Composite Spruce Lumber
        { "CottonCarpetItem", "#a47d00" },                        // T5 Cotton Carpet
        { "FlatSteelItem", "#a7a7aa" },                           // T5 Flat Steel
        { "FramedGlassItem", "#679db7" },                         // T5 Framed Glass
        { "NylonCarpetItem", "#4a84ba" },                         // T5 Nylon Carpet
        { "WoolCarpetItem", "#975c00" },                          // T5 Wool Carpet
    }.ToFrozenDictionary(StringComparer.Ordinal);
}
